#!/bin/sh
# dependencies(these might be good) --> grep, sed, curl

# Pre
prog="lpz-cli"
saveDir="/usr/share/lpz-cli/"
lpz_file="/usr/share/lpz-cli/lpz_file.txt"

# Color Codes
c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"
c_blue="\033[1;34m"
c_magenta="\033[1;35m"
c_cyan="\033[1;36m"
c_reset="\033[0m"
msgLine="${c_yellow}-------------\n"

msg_help () {
	while IFS= read line; do
		printf "%s\n" "$line"
	done <<-EOF
	USAGE: $prog <query>
	EOF
}

# Kill/exit
die () {
  printf "$c_red %s$c_reset\n" "$*" >&2
  exit 1
}

createFileDir() {
	if [ -f $lpz_file ]; then
		continue

	else
		printf "$c_red File $lpz_file does not already exist.\n"
		sleep 1
		if [ -d "$saveDir" ]; then
			continue

		else
			sudo mkdir $saveDir
		fi

		sudo touch $lpz_file
		sudo chmod 777 $lpz_file
		printf "$c_yellow Created file $lpz_file\n $c_reset"
	fi
}

# Actually calling the create function.
createFileDir

while :; do
  tput reset
  printf "$msgLine"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_green%s$c_reset\n" "s" "search"
	printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "l" "output log file"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_red%s$c_reset\n" "q" "exit"
  printf "$msgLine\n"
  printf "${c_yellow}Enter choice:${c_cyan} "
  read choice

  case $choice in
    s)
			continue
      ;;

		l)
			if [ -f $lpz_file ]; then
				if [[ -z $(grep '[^[:space:]]' $lpz_file) ]] ; then
				  echo "Empty file"
				fi
			else
				createFileDir
			fi

			;;

    q)
      break
      ;;
    *)
      die "invalid choice"
      ;;
  esac
done
