#!/bin/sh
# dependencies(these might be good) --> grep, sed, curl

c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"
c_blue="\033[1;34m"
c_magenta="\033[1;35m"
c_cyan="\033[1;36m"
c_reset="\033[0m"

help_text () {
	while IFS= read line; do
		printf "%s\n" "$line"
	done <<-EOF
	USAGE: $prog <query>
	 -h	 show this help message
	EOF
}

die () {
  printf "$c_red %s$c_reset\n" "$*" >&2
  exit 1
}

while getopts ":h:p:" OPT; do
    case $OPT in
        h)
          printf "$c_yellow help text"
          exit 0
          ;;
    esac
done

while :; do
  printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "r" "r option"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "a" "a option"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "h" "h option"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_red%s$c_reset\n\n" "q" "exit"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_cyan%s$c_reset\n" "l" "l option"
  printf "$c_blue[${c_cyan}%s$c_blue] $c_cyan%s$c_reset\n" "cl" "cl option"
  printf "${c_blue}Enter choice:${c_green} "
  read choice

  case $choice in
    n)
      continue
      ;;
    p)
      continue
      ;;
    s)
      continue
      ;;
    r)
      continue
      ;;
    a)
      continue
      ;;
    h)
      continue
      ;;
    q)
      break
      ;;
    l)
      continue
      ;;
    cl)
      continue
      ;;
    *)
      die "invalid choice"
      ;;
  esac


done
